language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: ObYyf3do0j6I3N0B22Mp7iWypLj9Jp+exezHxS+Y2jIFULW6c+Rdej6zyufep2DECKoF9HA4Fn+N91r/nZASB7FNH6cI4nAHQ29YlXcf+ndsTQVrOgZJQ51+7YRsQXM7Fdlz7iSH4QaFpAJPBSxKszLZj1/yT6e0IHWRPeDjR5c=
  - secure: DgTBMD+mVXSSYXQEhYMqXs6TGFqvx9VCV0rCtDFJJCrrcQilKB/4PMYP3YlWlkrbATi/WT3dau8xVDpq4Vmtd4YD4LTXSPQ9dISnBNmVmmBzY1l91kGF05u8U4c3fiagOrWa9ab6SttEqS3C4AGXzoDgTNGt2YEyJKl2q4yi51M=
